language: objective-c
before_install:
  - brew update
  - brew reinstall xctool
  - gem update cocoapods
xcode_workspace: WBWebViewConsole.xcworkspace
xcode_scheme: WBWebViewConsole
xcode_sdk:
  - iphonesimulator8.1