language: objective-c
before_install:
  - brew update
  - brew reinstall xctool
  - gem update cocoapods
xcode_project: WBWebViewConsole.xcodeproj
xcode_scheme: WBWebViewConsole
xcode_sdk:
  - iphonesimulator9.3
